# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  test_pull_request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
#    - run: npm ci
#    - run: npm test
    - run: |
        `cat >~/.netrc <<EOF
                  machine api.heroku.com
                      login $EMAIL
                      password $HEROKU_AUTH_TOKEN
                  machine git.heroku.com
                      login $EMAIL
                      password $HEROKU_AUTH_TOKEN
                  EOF`
      env:
        EMAIL: isser_troy_gagan@dlsu.edu.ph
        HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}

    - name: "Add remote"
      shell: "bash"
      run: |
        heroku git:remote --app dlsu-pahiram-services
    - name: "Push to heroku"
      shell: "bash"
      run: |
        git push heroku HEAD:master