# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  test_pull_request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm test

    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@v8.0.18
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix: ''

#    - name: Deploy to Heroku
#      uses: AkhileshNS/heroku-deploy@v3.6.8
#      with:
#        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#        heroku_app_name: dlsu-pahiram-services
#        heroku_email: keith_gabriel_badulis@dlsu.edu.ph
#        branch: 'master'

    - name: Deploying Production to Heroku 🖥️
      run: |
        git init
        git add .
        git commit -m 'Release V !!version'
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/dlsu-pahiram-services.git
        git push heroku master -f
#        working-directory: ./server

