# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Deployment

on:
  push:
    branches: [master]

jobs:
  test_pull_request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm ci
    - run: npm test
      -
    - name: Deploy to Heroku
      env:
        HEROKU_APP_NAME: "dlsu-pahiram-services"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:dcd9ff4d-a579-4a09-b4f3-f2546f00a49b@git.heroku.com/$HEROKU_APP_NAME.git origin/master:master
